import test from "node:test";
import assert from "node:assert/strict";
import { HermesTwoStageSkillStrategy, RetrievalRerankSkillStrategy, SKILL_OUTCOMES, retrieveSkills, stableBatches } from "../packages/skill-routing/src/index.js";

const skill=(id,description=id,metadata={})=>({id,name:id,description,relativePath:`skills/${id}/SKILL.md`,sourceHash:`hash-${id}`,metadata});
const skills=[skill("database","PostgreSQL database schema and migrations",{domain:"backend"}),skill("testing","Regression tests and test automation",{phase:"testing"}),skill("frontend","React browser interface"),skill("documentation","Technical documentation and guides"),skill("security","Security threat review"),skill("deployment","Production release deployment")];
const catalog={hash:"catalog",source:{type:"ecc",root:"fixture",git_commit:null,git_dirty:null},skills};
const task=(overrides={})=>({id:"task",text:"Fix PostgreSQL migration and add regression tests",createdAt:"now",...overrides});
const wait=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));

class MockEngine {
  constructor({choice,noul}={}) { this.choiceHandler=choice;this.noulHandler=noul;this.choiceCalls=[];this.noulCalls=[];this.active=0;this.maxActive=0; }
  async track(fn) { this.active++;this.maxActive=Math.max(this.maxActive,this.active);try{return await fn()}finally{this.active--} }
  choice(input) { this.choiceCalls.push(input);return this.track(()=>this.choiceHandler(input,this.choiceCalls.length-1)); }
  noul(input) { this.noulCalls.push(input);return this.track(()=>this.noulHandler(input,this.noulCalls.length-1)); }
}

function choiceFor(criteria,picks={}) { const probabilities={};for(const id of Object.keys(criteria)) probabilities[id]=picks[id]??0;const choice=Object.entries(probabilities).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0];return {choice,probabilities,confidence:0.8,provider:{name:"mock",model:"jev-test"},usage:{input_tokens:1,output_tokens:1},latency_ms:1}; }

test("Hermes batching is stable and bounded concurrency is observable",async()=>{assert.deepEqual(stableBatches(skills,2).map((batch)=>batch.map((x)=>x.id)),[["database","testing"],["frontend","documentation"],["security","deployment"]]);const engine=new MockEngine({choice:async(input,index)=>{await wait([20,5,10][index]);return choiceFor(input.criteria,{[Object.keys(input.criteria)[0]]:0.8})},noul:async()=>({probability_true:0.9,probability_false:0.1})});const proposal=await new HermesTwoStageSkillStrategy({decisionEngine:engine,batchSize:2,concurrency:2}).route({task:task(),catalog});assert.ok(engine.maxActive<=2);assert.equal(proposal.decision.provenance.batchCount,3);assert.deepEqual(proposal.decision.provenance.batchSizes,[2,2,2])});

test("Hermes aggregates and deduplicates survivors in stable probability order",async()=>{const engine=new MockEngine({choice:async(input,index)=>{await wait(index===0?15:1);const ids=Object.keys(input.criteria);return choiceFor(input.criteria,{[ids[0]]:0.6,[ids[1]]:0.3,database:0.99})},noul:async(input)=>({probability_true:input.instructions.includes("database")?0.9:0.6,probability_false:0.1})});const proposal=await new HermesTwoStageSkillStrategy({decisionEngine:engine,batchSize:3,concurrency:2,finalists:4}).route({task:task(),catalog});const survivors=proposal.decision.provenance.stage1Survivors.map((x)=>x.id);assert.equal(new Set(survivors).size,survivors.length);assert.deepEqual(survivors,["database","frontend","deployment","security"]);assert.deepEqual(proposal.decision.selectedSkillIds,["database","deployment","frontend"])});

test("Hermes Stage 2 accepts and rejects survivors independently",async()=>{const engine=new MockEngine({choice:async(input)=>choiceFor(input.criteria,{database:0.7,testing:0.2}),noul:async(input)=>input.instructions.includes("database")?{probability_true:0.8,probability_false:0.2}:{probability_true:0.2,probability_false:0.8}});const proposal=await new HermesTwoStageSkillStrategy({decisionEngine:engine,batchSize:10,finalists:2,verificationThreshold:0.5}).route({task:task(),catalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.SELECTED);assert.deepEqual(proposal.decision.selectedSkillIds,["database"]);assert.equal(proposal.decision.provenance.policy.verificationThreshold,0.5);assert.deepEqual(proposal.decision.provenance.stage2.map((x)=>[x.id,x.accepted]),[["database",true],["testing",false]])});

test("Hermes returns NO_SKILL for no survivors or all rejected",async()=>{const noneEngine=new MockEngine({choice:async(input)=>choiceFor(input.criteria,{__no_skill__:1}),noul:async()=>{throw new Error("not called")}});const none=await new HermesTwoStageSkillStrategy({decisionEngine:noneEngine,batchSize:10}).route({task:task(),catalog});assert.equal(none.decision.outcome,SKILL_OUTCOMES.NO_SKILL);assert.equal(none.decision.reason,"no_stage1_survivors");const rejectEngine=new MockEngine({choice:async(input)=>choiceFor(input.criteria,{database:0.8}),noul:async()=>({probability_true:0.1,probability_false:0.9})});const rejected=await new HermesTwoStageSkillStrategy({decisionEngine:rejectEngine,batchSize:10,finalists:1}).route({task:task(),catalog});assert.equal(rejected.decision.outcome,SKILL_OUTCOMES.NO_SKILL);assert.equal(rejected.decision.reason,"stage2_rejected_all")});

test("Hermes provider failure is ERROR, never NO_SKILL",async()=>{const engine=new MockEngine({choice:async()=>{const error=new Error("offline");error.code="network_failure";throw error},noul:async()=>({})});const proposal=await new HermesTwoStageSkillStrategy({decisionEngine:engine,batchSize:2}).route({task:task(),catalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.ERROR);assert.equal(proposal.decision.noSkill,false);assert.equal(proposal.decision.error.code,"network_failure");assert.equal(proposal.decision.provenance.failureStage,"stage1")});

test("Hermes output ordering is independent of asynchronous completion order",async()=>{async function run(delays){const engine=new MockEngine({choice:async(input,index)=>{await wait(delays[index]);const id=Object.keys(input.criteria)[0];return choiceFor(input.criteria,{[id]:0.7})},noul:async()=>({probability_true:0.8,probability_false:0.2})});const result=await new HermesTwoStageSkillStrategy({decisionEngine:engine,batchSize:2,concurrency:3}).route({task:task(),catalog});return {selected:result.decision.selectedSkillIds,candidates:result.candidates.map((x)=>x.id),survivors:result.decision.provenance.stage1Survivors.map((x)=>x.id)}}assert.deepEqual(await run([20,1,10]),await run([1,20,5]))});

test("local retrieval is deterministic, canonical, observable, and reduces the catalog",()=>{const first=retrieveSkills("PostgreSQL migration regression test",skills,3);const second=retrieveSkills("PostgreSQL migration regression test",[...skills].reverse(),3);assert.deepEqual(first,second);assert.ok(first.length<skills.length);assert.deepEqual(first.map((x)=>x.id),["testing","database"]);assert.ok(first[0].score>0)});

test("retrieval rerank sends only shortlist metadata and can select a canonical skill",async()=>{const engine=new MockEngine({choice:async(input)=>choiceFor(input.criteria,{testing:0.75,database:0.2}),noul:async()=>({probability_true:0.85,probability_false:0.15})});const proposal=await new RetrievalRerankSkillStrategy({decisionEngine:engine,shortlistSize:2}).route({task:task(),catalog});assert.deepEqual(Object.keys(engine.choiceCalls[0].criteria).sort(),["__no_skill__","database","testing"]);assert.match(engine.choiceCalls[0].criteria.database,/domain/);assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.SELECTED);assert.deepEqual(proposal.decision.selectedSkillIds,["testing"]);assert.deepEqual(proposal.decision.provenance.retrievalShortlist.map((x)=>x.id),["testing","database"])});

test("retrieval fit rejection is semantic NO_SKILL",async()=>{const engine=new MockEngine({choice:async(input)=>choiceFor(input.criteria,{database:0.8}),noul:async()=>({probability_true:0.2,probability_false:0.8})});const proposal=await new RetrievalRerankSkillStrategy({decisionEngine:engine}).route({task:task(),catalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.NO_SKILL);assert.equal(proposal.decision.reason,"fit_rejected");assert.equal(proposal.decision.error,null)});

test("retrieval provider failure is ERROR, not NO_SKILL",async()=>{const engine=new MockEngine({choice:async()=>{const error=new Error("provider");error.code="rate_limit";throw error},noul:async()=>({})});const proposal=await new RetrievalRerankSkillStrategy({decisionEngine:engine}).route({task:task(),catalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.ERROR);assert.equal(proposal.decision.error.code,"rate_limit");assert.equal(proposal.decision.provenance.failureStage,"rerank")});

test("supplied task and session context reaches retrieval and semantic judgment",async()=>{const seen=[];const engine=new MockEngine({choice:async(input)=>{seen.push(input.state);return choiceFor(input.criteria,{database:0.8})},noul:async(input)=>{seen.push(input.state);return {probability_true:0.8,probability_false:0.2}}});const proposal=await new RetrievalRerankSkillStrategy({decisionEngine:engine}).route({task:task({text:"Now add the regression test",recentContext:[{text:"Fix the PostgreSQL migration"}]}),catalog,session:{recentContext:[{text:"Database schema remains the active task"}]}});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.SELECTED);assert.ok(seen.every((state)=>state.includes("PostgreSQL migration")&&state.includes("Database schema")))});

test("Hermes partial Stage 1 failure is explicit and identifies the failed batch",async()=>{const engine=new MockEngine({choice:async(input,index)=>{if(index===1){const error=new Error("batch failed");error.code="rate_limit";throw error}return choiceFor(input.criteria,{[Object.keys(input.criteria)[0]]:0.8})},noul:async()=>({probability_true:0.8,probability_false:0.2})});const proposal=await new HermesTwoStageSkillStrategy({decisionEngine:engine,batchSize:2,concurrency:2}).route({task:task(),catalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.ERROR);assert.equal(proposal.decision.noSkill,false);assert.equal(proposal.decision.error.code,"rate_limit");assert.equal(proposal.decision.provenance.failureStage,"stage1");assert.equal(proposal.decision.provenance.failureBatchIndex,1);assert.ok(proposal.decision.provenance.jevCallCount>=2)});

test("malformed semantic probabilities are errors rather than NO_SKILL or acceptance",async()=>{const hermesEngine=new MockEngine({choice:async(input)=>choiceFor(input.criteria,{database:0.8}),noul:async()=>({probability_true:undefined,probability_false:undefined})});const hermes=await new HermesTwoStageSkillStrategy({decisionEngine:hermesEngine,batchSize:10,finalists:1}).route({task:task(),catalog});assert.equal(hermes.decision.outcome,SKILL_OUTCOMES.ERROR);assert.equal(hermes.decision.reason,"strategy_invalid_decision");assert.equal(hermes.decision.provenance.failureStage,"stage2");const retrievalEngine=new MockEngine({choice:async(input)=>choiceFor(input.criteria,{database:0.8}),noul:async()=>({probability_true:Number.NaN,probability_false:0.2})});const retrieval=await new RetrievalRerankSkillStrategy({decisionEngine:retrievalEngine}).route({task:task(),catalog});assert.equal(retrieval.decision.outcome,SKILL_OUTCOMES.ERROR);assert.equal(retrieval.decision.reason,"strategy_invalid_decision");assert.equal(retrieval.decision.provenance.failureStage,"fit")});

test("retrieval rejects a semantic choice outside the shortlist",async()=>{const engine=new MockEngine({choice:async()=>({choice:"security",probabilities:{security:1},confidence:1}),noul:async()=>{throw new Error("not called")}});const proposal=await new RetrievalRerankSkillStrategy({decisionEngine:engine,shortlistSize:1}).route({task:task(),catalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.ERROR);assert.equal(proposal.decision.error.code,"off_shortlist_choice");assert.equal(proposal.decision.provenance.failureStage,"rerank");assert.equal(engine.noulCalls.length,0)});

test("retrieval handles small catalogs and zero lexical overlap without arbitrary fill",async()=>{const oneSkill=[skill("database","PostgreSQL database schema")];assert.deepEqual(retrieveSkills("PostgreSQL",oneSkill,8).map((item)=>item.id),["database"]);assert.deepEqual(retrieveSkills("watercolor portrait",oneSkill,8),[]);const engine=new MockEngine({choice:async()=>{throw new Error("not called")},noul:async()=>{throw new Error("not called")}});const proposal=await new RetrievalRerankSkillStrategy({decisionEngine:engine}).route({task:task({text:"Paint a watercolor portrait",recentContext:[]}),catalog:{...catalog,skills:oneSkill}});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.NO_DECISION);assert.equal(proposal.decision.reason,"retrieval_empty");assert.equal(engine.choiceCalls.length,0)});

test("Hermes receives supplied task and session context in both semantic stages",async()=>{const seen=[];const engine=new MockEngine({choice:async(input)=>{seen.push(input.state);return choiceFor(input.criteria,{database:0.8})},noul:async(input)=>{seen.push(input.state);return {probability_true:0.8,probability_false:0.2}}});const proposal=await new HermesTwoStageSkillStrategy({decisionEngine:engine,batchSize:10,finalists:1}).route({task:task({text:"Now add the regression test",recentContext:[{text:"Fix the PostgreSQL migration"}]}),catalog,session:{recentContext:[{text:"Database schema remains the active task"}]}});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.SELECTED);assert.equal(seen.length,2);assert.ok(seen.every((state)=>state.includes("PostgreSQL migration")&&state.includes("Database schema")))});

test("Hermes rejects a Stage 1 choice outside its canonical batch",async()=>{const engine=new MockEngine({choice:async()=>({choice:"not-in-catalog",probabilities:{"not-in-catalog":1},confidence:1}),noul:async()=>{throw new Error("not called")}});const proposal=await new HermesTwoStageSkillStrategy({decisionEngine:engine,batchSize:2}).route({task:task(),catalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.ERROR);assert.equal(proposal.decision.reason,"strategy_invalid_decision");assert.equal(proposal.decision.error.code,"off_batch_choice");assert.equal(proposal.decision.provenance.failureBatchIndex,0);assert.equal(engine.noulCalls.length,0)});
