import test from "node:test";
import assert from "node:assert/strict";
import { deriveEccHierarchy, EccHermesSkillStrategy, EccHierarchySkillStrategy, SKILL_OUTCOMES, prepareEccHermesCatalog } from "../packages/skill-routing/src/index.js";

const skill=(id,description=id,metadata={})=>({id,name:id,description,relativePath:`skills/${id}/SKILL.md`,sourceHash:`hash-${id}`,metadata});
const skills=[skill("database","PostgreSQL migrations",{category:"backend"}),skill("testing","Regression tests",{tags:"quality"}),skill("frontend","React interface",{family:"web"})];
const catalog={hash:"catalog",source:{type:"ecc",root:"fixture",git_commit:null,git_dirty:null},skills};
const hierarchyCatalog={...catalog,modules:[{id:"data",kind:"skills",description:"Data work",stability:"stable",paths:["skills/database"]},{id:"quality",kind:"skills",description:"Quality work",stability:"stable",paths:["skills/testing"]},{id:"web",kind:"orchestration",description:"Web work",stability:"beta",paths:["scripts/web-runtime.js","skills/frontend"]}]};
const task={id:"task",text:"Fix the PostgreSQL migration",createdAt:"now"};

class MockEngine {
  constructor({choice,noul}) { this.choiceHandler=choice;this.noulHandler=noul;this.choiceCalls=[];this.noulCalls=[]; }
  choice(input) { this.choiceCalls.push(input);return this.choiceHandler(input,this.choiceCalls.length-1); }
  noul(input) { this.noulCalls.push(input);return this.noulHandler(input,this.noulCalls.length-1); }
}

function choiceFor(criteria,picks={}) { const probabilities=Object.fromEntries(Object.keys(criteria).map((id)=>[id,picks[id]??0]));const choice=Object.entries(probabilities).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0][0];return {choice,probabilities,confidence:0.8,provider:{name:"mock"},usage:null,latency_ms:1}; }

test("ECC preprocessor excludes structurally invalid candidates before JEV",()=>{const input={task,catalog:{...catalog,skills:[skills[0],null,{id:"",description:"broken"},skills[1]]}};const prepared=prepareEccHermesCatalog(input);assert.deepEqual(prepared.catalog.skills.map((item)=>item.id),["database","testing"]);assert.deepEqual(prepared.provenance.hardExcludedCandidates.map((item)=>item.reason),["invalid_canonical_identity","invalid_canonical_identity"])});

test("runtime visibility is an authoritative hard availability boundary",async()=>{const engine=new MockEngine({choice:async(input)=>{assert.deepEqual(Object.keys(input.criteria).sort(),["__no_skill__","database"]);return choiceFor(input.criteria,{database:0.9})},noul:async()=>({probability_true:0.9,probability_false:0.1})});const proposal=await new EccHermesSkillStrategy({decisionEngine:engine,batchSize:10}).route({task,catalog,runtime:{runtime:"test",visibleSkills:["database"]}});assert.deepEqual(proposal.decision.selectedSkillIds,["database"]);assert.deepEqual(proposal.decision.provenance.hardExcludedCandidates,[{id:"testing",reason:"not_runtime_visible"},{id:"frontend",reason:"not_runtime_visible"}]);assert.equal(proposal.decision.provenance.remainingCandidateCount,1)});

test("soft ECC metadata annotates candidates without hard exclusion",async()=>{const engine=new MockEngine({choice:async(input)=>{assert.match(input.criteria.testing,/metadata\.tags=quality/);return choiceFor(input.criteria,{testing:0.9})},noul:async(input)=>{assert.match(input.criteria.true,/metadata\.tags=quality/);return {probability_true:0.8,probability_false:0.2}}});const proposal=await new EccHermesSkillStrategy({decisionEngine:engine,batchSize:10,finalists:1}).route({task,catalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.SELECTED);assert.deepEqual(proposal.decision.selectedSkillIds,["testing"]);assert.equal(proposal.decision.provenance.hardExcludedCandidates.length,0);assert.deepEqual(proposal.decision.provenance.eccSoftSignalsUsed.map((item)=>item.id),["database","frontend","testing"])});

test("hybrid composes existing Hermes stages and preserves canonical IDs",async()=>{const engine=new MockEngine({choice:async(input)=>choiceFor(input.criteria,{database:0.7,testing:0.2}),noul:async(input)=>({probability_true:input.instructions.includes("database")?0.9:0.1,probability_false:input.instructions.includes("database")?0.1:0.9})});const proposal=await new EccHermesSkillStrategy({decisionEngine:engine,batchSize:10,finalists:2}).route({task,catalog});assert.equal(proposal.strategy,"skill/ecc-hermes-v1");assert.deepEqual(proposal.decision.selectedSkillIds,["database"]);assert.deepEqual(proposal.decision.provenance.hermes.stage1Survivors.map((item)=>item.id),["database","testing"]);assert.equal(proposal.decision.provenance.hermes.stage2.length,2);assert.equal(engine.choiceCalls.length,1);assert.equal(engine.noulCalls.length,2)});

test("hybrid provider failure remains ERROR rather than NO_SKILL",async()=>{const engine=new MockEngine({choice:async()=>{const error=new Error("offline");error.code="network_failure";throw error},noul:async()=>({})});const proposal=await new EccHermesSkillStrategy({decisionEngine:engine,batchSize:10}).route({task,catalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.ERROR);assert.equal(proposal.decision.noSkill,false);assert.equal(proposal.decision.error.code,"network_failure");assert.equal(proposal.decision.provenance.hermes.failureStage,"stage1")});

test("hybrid preserves Hermes semantic NO_SKILL",async()=>{const engine=new MockEngine({choice:async(input)=>choiceFor(input.criteria,{database:0.8}),noul:async()=>({probability_true:0.1,probability_false:0.9})});const proposal=await new EccHermesSkillStrategy({decisionEngine:engine,batchSize:10,finalists:1}).route({task,catalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.NO_SKILL);assert.equal(proposal.decision.reason,"stage2_rejected_all");assert.equal(proposal.decision.error,null)});

test("ECC hierarchy derivation has stable group IDs and membership",()=>{const first=deriveEccHierarchy(hierarchyCatalog);const second=deriveEccHierarchy({...hierarchyCatalog,skills:[...skills].reverse(),modules:[...hierarchyCatalog.modules].reverse()});assert.equal(first.supported,true);assert.deepEqual(first,second);assert.deepEqual(first.groups.map(({id,memberIds})=>({id,memberIds})),[{id:"data",memberIds:["database"]},{id:"quality",memberIds:["testing"]},{id:"web",memberIds:["frontend"]}])});

test("selected hierarchy group constrains downstream Hermes candidates",async()=>{const engine=new MockEngine({choice:async(input,index)=>index===0?choiceFor(input.criteria,{quality:0.9}):choiceFor(input.criteria,{testing:0.9}),noul:async()=>({probability_true:0.8,probability_false:0.2})});const proposal=await new EccHierarchySkillStrategy({decisionEngine:engine,batchSize:10,finalists:1}).route({task,catalog:hierarchyCatalog});assert.deepEqual(Object.keys(engine.choiceCalls[1].criteria).sort(),["__no_skill__","testing"]);assert.deepEqual(proposal.decision.selectedSkillIds,["testing"]);assert.equal(proposal.decision.provenance.selectedGroupId,"quality");assert.equal(proposal.decision.provenance.reducedCandidateCount,1);assert.equal(proposal.decision.provenance.hermes.initialCandidateCount,1)});

test("hierarchy rejects an invalid group returned by JEV",async()=>{const engine=new MockEngine({choice:async()=>({choice:"invented",probabilities:{invented:1},confidence:1}),noul:async()=>{throw new Error("not called")}});const proposal=await new EccHierarchySkillStrategy({decisionEngine:engine}).route({task,catalog:hierarchyCatalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.ERROR);assert.equal(proposal.decision.error.code,"invalid_hierarchy_group");assert.equal(proposal.decision.provenance.failureStage,"group_selection");assert.equal(engine.noulCalls.length,0)});

test("hierarchy group selection preserves NO_SKILL",async()=>{const engine=new MockEngine({choice:async(input)=>choiceFor(input.criteria,{__no_group__:1}),noul:async()=>{throw new Error("not called")}});const proposal=await new EccHierarchySkillStrategy({decisionEngine:engine}).route({task,catalog:hierarchyCatalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.NO_SKILL);assert.equal(proposal.decision.reason,"no_relevant_ecc_group");assert.equal(engine.choiceCalls.length,1);assert.equal(engine.noulCalls.length,0)});

test("hierarchy provider failure is ERROR rather than NO_SKILL",async()=>{const engine=new MockEngine({choice:async()=>{const error=new Error("offline");error.code="network_failure";throw error},noul:async()=>({})});const proposal=await new EccHierarchySkillStrategy({decisionEngine:engine}).route({task,catalog:hierarchyCatalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.ERROR);assert.equal(proposal.decision.noSkill,false);assert.equal(proposal.decision.error.code,"network_failure")});

test("hierarchy is explicitly unsupported without complete module membership",async()=>{const incomplete={...hierarchyCatalog,modules:[hierarchyCatalog.modules[0]]};const detection=deriveEccHierarchy(incomplete);assert.equal(detection.supported,false);assert.deepEqual(detection.unmappedSkillIds,["frontend","testing"]);const engine=new MockEngine({choice:async()=>{throw new Error("not called")},noul:async()=>{throw new Error("not called")}});const proposal=await new EccHierarchySkillStrategy({decisionEngine:engine}).route({task,catalog:incomplete});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.UNSUPPORTED);assert.equal(proposal.decision.reason,"incomplete_or_ambiguous_module_membership");assert.equal(engine.choiceCalls.length,0)});
