import test from "node:test";
import assert from "node:assert/strict";
import { EccNativeSkillStrategy, SKILL_OUTCOMES, canonicalSkills } from "../packages/skill-routing/src/index.js";

const catalog={hash:"catalog-hash",source:{type:"ecc",root:"fixture",git_commit:null,git_dirty:null},skills:[{id:"database-patterns",name:"Database Patterns",description:"PostgreSQL schema migrations and persistence",relativePath:"skills/database-patterns/SKILL.md",sourceHash:"db"},{id:"testing",name:"Testing",description:"Regression tests and test infrastructure",relativePath:"skills/testing/SKILL.md",sourceHash:"test"},{id:"frontend",name:"Frontend",description:"React user interfaces",relativePath:"skills/frontend/SKILL.md",sourceHash:"ui"}]};
const task=(overrides={})=>({id:"task-1",text:"Fix the PostgreSQL migration",createdAt:"2026-09-29T00:00:00Z",...overrides});

test("canonical skill candidates retain ECC identity and provenance",()=>{const skills=canonicalSkills(catalog);assert.deepEqual(skills.map((skill)=>skill.id),["database-patterns","frontend","testing"]);assert.equal(skills[0].relativePath,"skills/database-patterns/SKILL.md");assert.equal(skills[0].sourceHash,"db")});
test("ECC baseline implements the common RouteProposal contract",async()=>{const proposal=await new EccNativeSkillStrategy().route({task:task(),catalog});assert.equal(proposal.component,"skills");assert.equal(proposal.strategy,"skill/ecc-native-v1");assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.SELECTED);assert.deepEqual(proposal.decision.selectedSkillIds,["database-patterns"]);assert.equal(proposal.decision.provenance.catalogHash,"catalog-hash")});
test("lexical miss is a non-semantic no-decision",async()=>{const proposal=await new EccNativeSkillStrategy().route({task:task({text:"hello"}),catalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.NO_DECISION);assert.equal(proposal.decision.noSkill,false);assert.equal(proposal.decision.error,null)});
test("known explicit skill is resolved without semantic routing",async()=>{const proposal=await new EccNativeSkillStrategy().route({task:task({text:"anything",explicitSkills:["testing"]}),catalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.SELECTED);assert.deepEqual(proposal.decision.selectedSkillIds,["testing"]);assert.equal(proposal.decision.provenance.path,"deterministic-explicit");assert.equal(proposal.decision.confidence,1)});
test("unknown explicit skill is no-decision rather than no-skill",async()=>{const proposal=await new EccNativeSkillStrategy().route({task:task({explicitSkills:["missing"]}),catalog});assert.equal(proposal.decision.outcome,SKILL_OUTCOMES.NO_DECISION);assert.equal(proposal.decision.noSkill,false);assert.deepEqual(proposal.decision.provenance.missing,["missing"])});
test("provided prior context participates in a follow-up route",async()=>{const proposal=await new EccNativeSkillStrategy().route({task:task({text:"now handle the migration",recentContext:[{text:"we are fixing PostgreSQL persistence"}]}),catalog,session:{recentContext:[{text:"database schema failure"}]}});assert.deepEqual(proposal.decision.selectedSkillIds,["database-patterns"])});
test("strategy consumes the supplied stable catalog without rediscovery",async()=>{const strategy=new EccNativeSkillStrategy();const first=await strategy.route({task:task(),catalog});const second=await strategy.route({task:task(),catalog});assert.equal(first.decision.provenance.candidateSnapshotHash,second.decision.provenance.candidateSnapshotHash);assert.equal(first.decision.provenance.catalogSource,catalog.source)});
